import type { NicheTemplate } from "@/lib/types";

const weekday = "8:00 AM – 6:00 PM";
const sat = "9:00 AM – 2:00 PM";
const closed = "Closed";

const defaultHours = {
  mon: weekday,
  tue: weekday,
  wed: weekday,
  thu: weekday,
  fri: weekday,
  sat,
  sun: closed,
};

/**
 * Config-driven niche templates. No real business data — placeholders only.
 * Wizard + demo seed must pull from these templates, never hardcode a shop.
 */
export const NICHE_TEMPLATES: NicheTemplate[] = [
  {
    id: "hvac",
    label: "HVAC",
    defaultTagline: "Reliable heating & cooling for your home",
    defaultHours,
    defaultServices: [
      { name: "AC Repair", description: "Diagnostic and repair for central AC", priceFrom: 89 },
      { name: "Furnace Tune-Up", description: "Seasonal safety and efficiency check", priceFrom: 99 },
      { name: "System Install", description: "New HVAC system installation quote", priceFrom: 0 },
    ],
    heroHints: ["Call for same-day help", "Licensed & insured", "Clear pricing before we start"],
    ctaLabel: "Book a service visit",
    accentHint: "sky",
  },
  {
    id: "plumber",
    label: "Plumber",
    defaultTagline: "Fast, clean plumbing done right",
    defaultHours,
    defaultServices: [
      { name: "Leak Repair", description: "Find and fix pipe or fixture leaks", priceFrom: 79 },
      { name: "Drain Clearing", description: "Clogged sink, tub, or main line", priceFrom: 99 },
      { name: "Water Heater Service", description: "Repair or replacement consult", priceFrom: 129 },
    ],
    heroHints: ["Call for emergencies", "Free estimates on planned work", "Licensed & insured"],
    ctaLabel: "Schedule plumbing help",
    accentHint: "cyan",
  },
  {
    id: "salon",
    label: "Salon",
    defaultTagline: "Look your best — book with ease",
    defaultHours: {
      mon: closed,
      tue: "10:00 AM – 7:00 PM",
      wed: "10:00 AM – 7:00 PM",
      thu: "10:00 AM – 7:00 PM",
      fri: "10:00 AM – 8:00 PM",
      sat: "9:00 AM – 5:00 PM",
      sun: closed,
    },
    defaultServices: [
      { name: "Haircut", description: "Cut and style", priceFrom: 45 },
      { name: "Color", description: "Full color or touch-up", priceFrom: 85 },
      { name: "Blowout", description: "Wash and professional blow dry", priceFrom: 40 },
    ],
    heroHints: ["Book online in minutes", "Starting prices listed", "Stylists who listen"],
    ctaLabel: "Book now",
    accentHint: "rose",
  },
  {
    id: "electrician",
    label: "Electrician",
    defaultTagline: "Licensed electrical work you can schedule",
    defaultHours: {
      mon: "8:00 AM – 6:00 PM",
      tue: "8:00 AM – 6:00 PM",
      wed: "8:00 AM – 6:00 PM",
      thu: "8:00 AM – 6:00 PM",
      fri: "8:00 AM – 6:00 PM",
      sat: "9:00 AM – 1:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Outlet / Switch Repair", description: "Diagnose and fix common electrical issues", priceFrom: 89 },
      { name: "Panel Upgrade Consult", description: "Safety check and upgrade options", priceFrom: 0 },
      { name: "Lighting Install", description: "Indoor/outdoor fixture installation", priceFrom: 129 },
    ],
    heroHints: ["Call for emergencies", "License # on request", "Upfront scope"],
    ctaLabel: "Get an estimate",
    accentHint: "amber",
  },
  {
    id: "roofing",
    label: "Roofing",
    defaultTagline: "Inspect, repair, replace — clear next steps",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Roof Inspection", description: "Full visual inspection with written notes", priceFrom: 0 },
      { name: "Leak Repair", description: "Find and fix active leaks", priceFrom: 199 },
      { name: "Full Re-Roof Quote", description: "Material options and timeline", priceFrom: 0 },
    ],
    heroHints: ["Call for storm damage", "Licensed & insured", "Estimates for planned work"],
    ctaLabel: "Get a roof estimate",
    accentHint: "orange",
  },
  {
    id: "landscaping",
    label: "Landscaping",
    defaultTagline: "Lawn, beds & seasonal care — quote before we start",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Lawn Care / Mowing", description: "Weekly or biweekly when true — quote after lawn size, access, and season check; no bait flat $/visit or $/acre", priceFrom: 0 },
      { name: "Beds / Mulch / Plantings", description: "Clean beds and plantings when true — firm price after existing beds and irrigation site check", priceFrom: 0 },
      { name: "Seasonal Cleanup / Recurring Plans", description: "Spring/fall reset or recurring care honesty — no fake same-day makeovers", priceFrom: 0 },
    ],
    heroHints: ["Lawn size/access/beds/irrigation/season assessed before firm price", "Quote before mow or install", "Seasonal & recurring honesty", "No bait flat $/visit or $/acre fees"],
    ctaLabel: "Get a landscaping quote",
    accentHint: "forest-green-warm-earth",
  },
  {
    id: "auto_detail",
    label: "Auto detailing",
    defaultTagline: "Interior, exterior & protection — quote before we start",
    defaultHours: {
      mon: "9:00 AM – 6:00 PM",
      tue: "9:00 AM – 6:00 PM",
      wed: "9:00 AM – 6:00 PM",
      thu: "9:00 AM – 6:00 PM",
      fri: "9:00 AM – 6:00 PM",
      sat: "9:00 AM – 4:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Exterior Wash / Paint Care", description: "Hand wash and protect when true — quote after vehicle size, condition, and location check; no bait flat package fees", priceFrom: 0 },
      { name: "Interior Detail", description: "Vacuum, wipe-down, glass when true — firm price after interior condition assessment", priceFrom: 0 },
      { name: "Full Detail / Ceramic Protection", description: "Inside + outside or ceramic when true — ceramic ≠ wash; no fake same-day shine guarantees", priceFrom: 0 },
    ],
    heroHints: ["Vehicle size/condition/location/package assessed before firm price", "Quote before wash or ceramic", "Interior/exterior honesty", "Ceramic ≠ wash — no bait flat package fees"],
    ctaLabel: "Get a detail quote",
    accentHint: "graphite-chrome",
  },
  {
    id: "cleaning",
    label: "Cleaning",
    defaultTagline: "Spotless spaces on a schedule you can count on",
    defaultHours: {
      mon: "8:00 AM – 5:00 PM",
      tue: "8:00 AM – 5:00 PM",
      wed: "8:00 AM – 5:00 PM",
      thu: "8:00 AM – 5:00 PM",
      fri: "8:00 AM – 5:00 PM",
      sat: "9:00 AM – 1:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Standard Clean", description: "Recurring home or office clean", priceFrom: 120 },
      { name: "Deep Clean", description: "Baseboards, appliances, detail work", priceFrom: 220 },
      { name: "Move-in / Move-out", description: "Empty-home reset", priceFrom: 250 },
    ],
    heroHints: ["Recurring default pricing", "Team you can meet", "Easy reschedule"],
    ctaLabel: "Book recurring",
    accentHint: "teal",
  },
  {
    id: "pest_control",
    label: "Pest control",
    defaultTagline: "Inspect, treat, prevent — without the scare tactics",
    defaultHours: {
      mon: "8:00 AM – 5:00 PM",
      tue: "8:00 AM – 5:00 PM",
      wed: "8:00 AM – 5:00 PM",
      thu: "8:00 AM – 5:00 PM",
      fri: "8:00 AM – 5:00 PM",
      sat: "9:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Home Inspection", description: "Identify activity and entry points", priceFrom: 0 },
      { name: "General Treatment", description: "Interior/exterior service visit", priceFrom: 149 },
      { name: "Quarterly Plan", description: "Ongoing prevention schedule", priceFrom: 99 },
    ],
    heroHints: ["Call for same-day help", "Licensed technicians", "Pet-aware options"],
    ctaLabel: "Book inspection",
    accentHint: "lime",
  },
  {
    id: "moving",
    label: "Moving",
    defaultTagline: "Moves that stay on plan — pack, load, deliver",
    defaultHours: {
      mon: "8:00 AM – 6:00 PM",
      tue: "8:00 AM – 6:00 PM",
      wed: "8:00 AM – 6:00 PM",
      thu: "8:00 AM – 6:00 PM",
      fri: "8:00 AM – 6:00 PM",
      sat: "8:00 AM – 4:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Local Move", description: "Apartment or home within the metro", priceFrom: 0 },
      { name: "Packing Help", description: "Full or partial packing labor", priceFrom: 199 },
      { name: "Long-Distance Quote", description: "Interstate move estimate", priceFrom: 0 },
    ],
    heroHints: ["Licensed & insured", "Fixed-scope options", "Arrival windows"],
    ctaLabel: "Get a moving quote",
    accentHint: "indigo",
  },
  {
    id: "painting",
    label: "Painting",
    defaultTagline: "Fresh walls, clean lines — estimate, prep, paint",
    defaultHours: {
      mon: "8:00 AM – 5:00 PM",
      tue: "8:00 AM – 5:00 PM",
      wed: "8:00 AM – 5:00 PM",
      thu: "8:00 AM – 5:00 PM",
      fri: "8:00 AM – 5:00 PM",
      sat: "9:00 AM – 1:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Interior Paint", description: "Rooms, trim, and ceilings", priceFrom: 0 },
      { name: "Exterior Paint", description: "Siding and outdoor surfaces", priceFrom: 0 },
      { name: "Cabinet Refinish", description: "Kitchen or bath cabinet refresh", priceFrom: 499 },
    ],
    heroHints: ["Written estimate", "Prep options clear", "Schedule when ready"],
    ctaLabel: "Request estimate",
    accentHint: "purple",
  },
  {
    id: "garage",
    label: "Garage door",
    defaultTagline: "Stuck door? Clear next step — call if we are open now",
    defaultHours: {
      mon: "7:00 AM – 7:00 PM",
      tue: "7:00 AM – 7:00 PM",
      wed: "7:00 AM – 7:00 PM",
      thu: "7:00 AM – 7:00 PM",
      fri: "7:00 AM – 7:00 PM",
      sat: "8:00 AM – 4:00 PM",
      sun: "On-call — ask when you call",
    },
    defaultServices: [
      { name: "Spring / Cable Repair", description: "Diagnose and repair common door failures", priceFrom: 0 },
      { name: "Opener Service", description: "Opener tune-up or replacement consult", priceFrom: 129 },
      { name: "New Door Quote", description: "Residential door options and install", priceFrom: 0 },
    ],
    heroHints: ["Hours listed honestly", "Service area up front", "Licensed & insured"],
    ctaLabel: "Get a repair quote",
    accentHint: "orange",
  },
  {
    id: "locksmith",
    label: "Locksmith",
    defaultTagline: "Locked out? Tap to call — real license, real hours",
    defaultHours: {
      mon: "8:00 AM – 8:00 PM",
      tue: "8:00 AM – 8:00 PM",
      wed: "8:00 AM – 8:00 PM",
      thu: "8:00 AM – 8:00 PM",
      fri: "8:00 AM – 8:00 PM",
      sat: "9:00 AM – 5:00 PM",
      sun: "On-call — ask when you call",
    },
    defaultServices: [
      { name: "Lockout Service", description: "Home or vehicle lockout help", priceFrom: 0 },
      { name: "Rekey", description: "Rekey locks after move or lost keys", priceFrom: 89 },
      { name: "Lock Install", description: "Deadbolt or smart-lock install consult", priceFrom: 129 },
    ],
    heroHints: ["TX DPS PSB # when licensed", "Hours honesty over fake 24/7", "Insured & bonded"],
    ctaLabel: "Request lockout help",
    accentHint: "amber",
  },
  {
    id: "janitorial",
    label: "Commercial cleaning",
    defaultTagline: "Facility cleaning quotes — clear scope, bonded team",
    defaultHours: {
      mon: "7:00 AM – 6:00 PM",
      tue: "7:00 AM – 6:00 PM",
      wed: "7:00 AM – 6:00 PM",
      thu: "7:00 AM – 6:00 PM",
      fri: "7:00 AM – 6:00 PM",
      sat: "By appointment",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Office Clean", description: "Nightly or recurring office service", priceFrom: 0 },
      { name: "Facility Deep Clean", description: "Floors, restrooms, high-touch areas", priceFrom: 0 },
      { name: "Janitorial Contract", description: "Multi-site recurring quote", priceFrom: 0 },
    ],
    heroHints: ["Bonded & insured", "Facility quote in a few fields", "Founder / team visible"],
    ctaLabel: "Request commercial quote",
    accentHint: "cyan",
  },
  {
    id: "towing",
    label: "Towing / roadside",
    defaultTagline: "Stranded? Tap to call — ETA honesty, real coverage",
    defaultHours: {
      mon: "24 hours — ask who answers",
      tue: "24 hours — ask who answers",
      wed: "24 hours — ask who answers",
      thu: "24 hours — ask who answers",
      fri: "24 hours — ask who answers",
      sat: "24 hours — ask who answers",
      sun: "24 hours — ask who answers",
    },
    defaultServices: [
      { name: "Emergency Tow", description: "Local tow to shop or home", priceFrom: 0 },
      { name: "Jump Start", description: "Battery boost roadside", priceFrom: 69 },
      { name: "Flatbed / Winch-Out", description: "Flatbed or stuck-vehicle help", priceFrom: 0 },
    ],
    heroHints: ["Text ZIP / mile-marker coverage", "TX TDLR # when licensed", "Dispatch quotes ETA on call"],
    ctaLabel: "Request dispatch callback",
    accentHint: "red",
  },
  {
    id: "water_damage",
    label: "Water damage",
    defaultTagline: "Water emergency? Call now — we work with insurance",
    defaultHours: {
      mon: "24 hours — ask who answers",
      tue: "24 hours — ask who answers",
      wed: "24 hours — ask who answers",
      thu: "24 hours — ask who answers",
      fri: "24 hours — ask who answers",
      sat: "24 hours — ask who answers",
      sun: "24 hours — ask who answers",
    },
    defaultServices: [
      { name: "Emergency Water Extraction", description: "Stop and remove standing water", priceFrom: 0 },
      { name: "Drying & Dehumidification", description: "Equipment and moisture monitoring", priceFrom: 0 },
      { name: "Insurance Documentation Help", description: "Photos and paperwork support — not claim approval", priceFrom: 0 },
    ],
    heroHints: ["IICRC credential when true", "Insurance process help (not coverage guarantees)", "Optional photo — never required"],
    ctaLabel: "Request callback",
    accentHint: "red",
  },
  {
    id: "fire_smoke",
    label: "Fire / smoke restoration",
    defaultTagline: "After the fire — call for board-up, soot, and water help",
    defaultHours: {
      mon: "24 hours — ask who answers",
      tue: "24 hours — ask who answers",
      wed: "24 hours — ask who answers",
      thu: "24 hours — ask who answers",
      fri: "24 hours — ask who answers",
      sat: "24 hours — ask who answers",
      sun: "24 hours — ask who answers",
    },
    defaultServices: [
      { name: "Emergency Board-Up", description: "Secure openings and limit secondary loss", priceFrom: 0 },
      { name: "Soot & Smoke Cleaning", description: "Structure and contents cleaning after fire", priceFrom: 0 },
      { name: "Insurance Documentation Help", description: "Photos and paperwork support — not claim approval", priceFrom: 0 },
    ],
    heroHints: ["Board-up Day-1", "FSRT / IICRC when true", "Firefighting water treated as second loss"],
    ctaLabel: "Request emergency callback",
    accentHint: "red",
  },
  {
    id: "mold_remediation",
    label: "Mold remediation",
    defaultTagline: "Suspected mold? Call for calm next steps — inspection honesty, no scare tactics",
    defaultHours: {
      mon: "8:00 AM – 5:00 PM",
      tue: "8:00 AM – 5:00 PM",
      wed: "8:00 AM – 5:00 PM",
      thu: "8:00 AM – 5:00 PM",
      fri: "8:00 AM – 5:00 PM",
      sat: "9:00 AM – 1:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Mold Assessment Guidance", description: "When to inspect, contain, or remediate — honest scope talk", priceFrom: 0 },
      { name: "Containment & Remediation", description: "Moisture source, containment, remove/treat porous materials", priceFrom: 0 },
      { name: "Insurance Documentation Help", description: "Photos and paperwork support — not claim approval", priceFrom: 0 },
    ],
    heroHints: ["IICRC when true", "TX TDLR assessor vs remediator separation", "Insurance docs help — not claim approval", "No same-visit inspect+remediate hero"],
    ctaLabel: "Request callback",
    accentHint: "teal",
  },
  {
    id: "tree_service",
    label: "Tree service",
    defaultTagline: "Storm damage or a risky limb? Call first — honest next steps, no fake ETAs",
    defaultHours: {
      mon: "7:00 AM – 6:00 PM",
      tue: "7:00 AM – 6:00 PM",
      wed: "7:00 AM – 6:00 PM",
      thu: "7:00 AM – 6:00 PM",
      fri: "7:00 AM – 6:00 PM",
      sat: "8:00 AM – 2:00 PM",
      sun: "Storm call-out when staffed — ask who answers",
    },
    defaultServices: [
      { name: "Storm / Emergency Tree Response", description: "Downed trees and hazardous limbs — dispatch honesty, no fake ETAs", priceFrom: 0 },
      { name: "Hazardous Tree Assessment", description: "Risk talk for leaning/damaged trees; ISA/TRAQ only when credentialed", priceFrom: 0 },
      { name: "Pruning & Removal", description: "Scheduled pruning, removals, and cleanup — HOA/insurance educational only", priceFrom: 0 },
    ],
    heroHints: ["Sticky tel: primary", "Powerline — utility first when lines involved", "ISA/TRAQ only when true", "No fake ETAs", "Insurance/HOA educational only"],
    ctaLabel: "Call for storm help",
    accentHint: "amber",
  },
  {
    id: "slab_leak",
    label: "Slab leak detection",
    defaultTagline: "Warm floors or a spiking bill? Call first — detect and prove the leak before any cut",
    defaultHours: {
      mon: "8:00 AM – 5:00 PM",
      tue: "8:00 AM – 5:00 PM",
      wed: "8:00 AM – 5:00 PM",
      thu: "8:00 AM – 5:00 PM",
      fri: "8:00 AM – 5:00 PM",
      sat: "9:00 AM – 1:00 PM",
      sun: "Emergency call-out when staffed — ask who answers",
    },
    defaultServices: [
      { name: "Slab Leak Detection", description: "Non-invasive locate — acoustic / thermal / pressure honesty; prove before cut", priceFrom: 0 },
      { name: "Repair / Tunnel / Reroute Guidance", description: "Method cards after proof — educational, not competing primary CTAs", priceFrom: 0 },
      { name: "Insurance Documentation Help", description: "Photos and paperwork support — educational only, not claim approval", priceFrom: 0 },
    ],
    heroHints: ["Sticky tel: primary", "Detection-first — no sight-unseen cut", "TSBPE + RMP # when true (TX)", "Clay/copper copy TX geos only", "Insurance educational only"],
    ctaLabel: "Call to schedule detection",
    accentHint: "cyan",
  },
  {
    id: "junk_removal",
    label: "Junk removal",
    defaultTagline: "Haul it out — clear volume quotes, dump fees up front",
    defaultHours: {
      mon: "7:00 AM – 6:00 PM",
      tue: "7:00 AM – 6:00 PM",
      wed: "7:00 AM – 6:00 PM",
      thu: "7:00 AM – 6:00 PM",
      fri: "7:00 AM – 6:00 PM",
      sat: "8:00 AM – 2:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Single-Item Pickup", description: "Couch, appliance, or mattress haul — quote by item/load", priceFrom: 0 },
      { name: "Garage / Estate Cleanout", description: "Whole-space cleanouts with load-based pricing", priceFrom: 0 },
      { name: "Construction Debris", description: "Job-site debris haul — dump fees quoted up front", priceFrom: 0 },
    ],
    heroHints: ["Insured trucks", "Dump fees quoted up front", "No fake same-day promises"],
    ctaLabel: "Request a junk quote",
    accentHint: "lime",
  },
  {
    id: "pressure_washing",
    label: "Pressure washing",
    defaultTagline: "Driveways, siding, decks — surface-safe wash quotes first",
    defaultHours: {
      mon: "8:00 AM – 6:00 PM",
      tue: "8:00 AM – 6:00 PM",
      wed: "8:00 AM – 6:00 PM",
      thu: "8:00 AM – 6:00 PM",
      fri: "8:00 AM – 6:00 PM",
      sat: "8:00 AM – 2:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Driveway / Walk Wash", description: "Concrete and walkway wash — quote by size/soil", priceFrom: 0 },
      { name: "House Soft Wash", description: "Siding soft wash with surface-safe methods", priceFrom: 0 },
      { name: "Patio / Deck Clean", description: "Patio, deck, or outdoor living clean — quote before wash", priceFrom: 0 },
    ],
    heroHints: ["Insured crew", "Surface-safe methods", "Quote before wash"],
    ctaLabel: "Request a wash quote",
    accentHint: "sky",
  },
  {
    id: "gutter_cleaning",
    label: "Gutter cleaning",
    defaultTagline: "Clear gutters & downspouts — soft-wash honesty, quote before climb",
    defaultHours: {
      mon: "8:00 AM – 6:00 PM",
      tue: "8:00 AM – 6:00 PM",
      wed: "8:00 AM – 6:00 PM",
      thu: "8:00 AM – 6:00 PM",
      fri: "8:00 AM – 6:00 PM",
      sat: "8:00 AM – 2:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Gutter Cleanout", description: "Hand-clear debris from gutters — quote by linear feet / access", priceFrom: 0 },
      { name: "Downspout Flush", description: "Clear clogged downspouts so water exits where it should", priceFrom: 0 },
      { name: "Soft Wash / Edge Rinse", description: "Soft-wash vs power honesty for fascia and roof edge — quote before climb", priceFrom: 0 },
    ],
    heroHints: ["Insured height work when true", "Soft-wash vs power honesty", "Quote before climb"],
    ctaLabel: "Request a gutter quote",
    accentHint: "copper",
  },
  {
    id: "window_cleaning",
    label: "Window cleaning",
    defaultTagline: "Clear glass, honest methods — quote before climb",
    defaultHours: {
      mon: "8:00 AM – 6:00 PM",
      tue: "8:00 AM – 6:00 PM",
      wed: "8:00 AM – 6:00 PM",
      thu: "8:00 AM – 6:00 PM",
      fri: "8:00 AM – 6:00 PM",
      sat: "8:00 AM – 2:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Interior / Exterior Windows", description: "Pane-by-pane clean — quote by count, stories, and access", priceFrom: 0 },
      { name: "Storefront / Commercial Glass", description: "Storefront and lobby glass — quote before climb", priceFrom: 0 },
      { name: "Screens & Soft Detail", description: "Glass-safe methods vs aggressive scrub — screens and tracks quoted honestly", priceFrom: 0 },
    ],
    heroHints: ["Insured height work when true", "Glass-safe methods", "Quote before climb"],
    ctaLabel: "Request a window quote",
    accentHint: "glass",
  },
  {
    id: "carpet_cleaning",
    label: "Carpet cleaning",
    defaultTagline: "Clean carpet, honest methods — quote before steam",
    defaultHours: {
      mon: "8:00 AM – 6:00 PM",
      tue: "8:00 AM – 6:00 PM",
      wed: "8:00 AM – 6:00 PM",
      thu: "8:00 AM – 6:00 PM",
      fri: "8:00 AM – 6:00 PM",
      sat: "8:00 AM – 2:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Room Carpet Clean", description: "Whole-room carpet clean — quote by rooms, soil level, and furniture move", priceFrom: 0 },
      { name: "Area Rugs & Spot Treat", description: "Rugs and spots quoted honestly — no bait flat fees", priceFrom: 0 },
      { name: "Pet / Kid-Safe Methods", description: "Pet- and kid-safe methods when true — quote before steam or pretreat", priceFrom: 0 },
    ],
    heroHints: ["Pet/kid-safe methods when true", "Quote before steam", "Room & rug honesty"],
    ctaLabel: "Request a carpet quote",
    accentHint: "seafoam",
  },
  {
    id: "appliance_repair",
    label: "Appliance repair",
    defaultTagline: "Broken appliance? Call first — diagnose before parts",
    defaultHours: {
      mon: "8:00 AM – 6:00 PM",
      tue: "8:00 AM – 6:00 PM",
      wed: "8:00 AM – 6:00 PM",
      thu: "8:00 AM – 6:00 PM",
      fri: "8:00 AM – 6:00 PM",
      sat: "8:00 AM – 2:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Refrigerator / Freezer", description: "Diagnose cooling, seals, ice — call before parts order", priceFrom: 0 },
      { name: "Washer / Dryer", description: "Spin, drain, heat issues — diagnose before parts", priceFrom: 0 },
      { name: "Oven / Range / Dishwasher", description: "Heat and cycle faults — honest diagnostic fee when true", priceFrom: 0 },
    ],
    heroHints: ["Licensed tech when true", "Diagnose before parts", "Honest diagnostic fee"],
    ctaLabel: "Call for appliance repair",
    accentHint: "slate-orange",
  },
  {
    id: "handyman",
    label: "Handyman",
    defaultTagline: "Odd jobs done right — quote, then schedule",
    defaultHours: {
      mon: "8:00 AM – 5:00 PM",
      tue: "8:00 AM – 5:00 PM",
      wed: "8:00 AM – 5:00 PM",
      thu: "8:00 AM – 5:00 PM",
      fri: "8:00 AM – 5:00 PM",
      sat: "9:00 AM – 1:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Punch List / Odd Jobs", description: "Mounting, patching, small fixes — written scope before work", priceFrom: 0 },
      { name: "Door / Trim / Hardware", description: "Adjustments and installs when in scope", priceFrom: 0 },
      { name: "Drywall Patch & Touch-up", description: "Small holes and paint match when materials available", priceFrom: 125 },
    ],
    heroHints: ["Written scope before work", "Licensed & insured when true", "No fake same-day"],
    ctaLabel: "Request a handyman quote",
    accentHint: "workbench-gold",
  },
  {
    id: "flooring",
    label: "Flooring",
    defaultTagline: "Hard floors done right — quote before install",
    defaultHours: {
      mon: "8:00 AM – 5:00 PM",
      tue: "8:00 AM – 5:00 PM",
      wed: "8:00 AM – 5:00 PM",
      thu: "8:00 AM – 5:00 PM",
      fri: "8:00 AM – 5:00 PM",
      sat: "9:00 AM – 1:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "LVP / Laminate Install", description: "Click-lock and glue-down — quote after material + subfloor check", priceFrom: 0 },
      { name: "Hardwood Install / Refinish", description: "Sand, stain, or new hardwood — firm price after assessment", priceFrom: 0 },
      { name: "Tile / Stone Flooring", description: "Layout and set — no bait flat sqft fees", priceFrom: 0 },
    ],
    heroHints: ["Subfloor assessed before firm price", "Quote before install", "No bait flat sqft fees"],
    ctaLabel: "Request a flooring quote",
    accentHint: "oak-copper",
  },
  {
    id: "fencing",
    label: "Fencing",
    defaultTagline: "Fences built right — quote before we dig",
    defaultHours: {
      mon: "8:00 AM – 5:00 PM",
      tue: "8:00 AM – 5:00 PM",
      wed: "8:00 AM – 5:00 PM",
      thu: "8:00 AM – 5:00 PM",
      fri: "8:00 AM – 5:00 PM",
      sat: "9:00 AM – 1:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Wood / Cedar Fence", description: "Privacy and picket — quote after linear footage, height, terrain, posts", priceFrom: 0 },
      { name: "Vinyl / Composite Fence", description: "Low-maintenance panels — firm price after HOA + site check", priceFrom: 0 },
      { name: "Chain-Link / Ornamental", description: "Security or decorative — no bait flat $/ft fees", priceFrom: 0 },
    ],
    heroHints: ["Length/height/terrain assessed before firm price", "Quote before build", "No bait flat $/ft fees"],
    ctaLabel: "Get a fence quote",
    accentHint: "cedar-sage",
  },
  {
    id: "concrete",
    label: "Concrete",
    defaultTagline: "Driveways & flatwork — quote before we pour",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Driveway Pour / Replace", description: "New or tear-out — quote after sqft, access, thickness, and prep", priceFrom: 0 },
      { name: "Patio / Sidewalk Flatwork", description: "Walks and outdoor pads — firm price after drainage + site check", priceFrom: 0 },
      { name: "Garage Floor / Broom Finish", description: "Interior slab or broom finish — no bait flat $/sqft fees", priceFrom: 0 },
    ],
    heroHints: ["Sqft/access/prep assessed before firm price", "Quote before pour", "No bait flat $/sqft fees"],
    ctaLabel: "Get a concrete quote",
    accentHint: "slate-amber",
  },
  {
    id: "siding",
    label: "Siding",
    defaultTagline: "Exterior siding — quote before we install",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Vinyl / Engineered Siding", description: "Replace or install — quote after material, grade, sqft, stories, and access", priceFrom: 0 },
      { name: "Fiber-Cement Clapboard", description: "Durable wood-look panels — firm price after substrate + site check", priceFrom: 0 },
      { name: "Wood / Cedar Siding", description: "Classic clapboard when true — no bait flat $/sqft or fake same-day install", priceFrom: 0 },
    ],
    heroHints: ["Material/grade/sqft/stories assessed before firm price", "Quote before install", "No bait flat $/sqft fees"],
    ctaLabel: "Get a siding quote",
    accentHint: "clapboard-coastal",
  },
  {
    id: "decking",
    label: "Decking",
    defaultTagline: "Decks & patio decks — quote before we build",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Wood Deck Build / Rebuild", description: "New or replace — quote after sqft, height, access, footing, and material", priceFrom: 0 },
      { name: "Composite / PVC Decking", description: "Low-maintenance boards when true — firm price after site + footing check", priceFrom: 0 },
      { name: "Railings / Stairs / Landing", description: "Code-aware when required — no bait flat $/sqft or fake same-day build", priceFrom: 0 },
    ],
    heroHints: ["Sqft/height/access/footing assessed before firm price", "Quote before build", "HOA/permit honesty when required", "No bait flat $/sqft fees"],
    ctaLabel: "Get a deck quote",
    accentHint: "teak-charcoal-sage",
  },
  {
    id: "masonry",
    label: "Masonry",
    defaultTagline: "Brick, stone & block — quote before we build or repair",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Brick Build / Repair", description: "New or tuckpoint — quote after sqft, access, mortar, height, and material", priceFrom: 0 },
      { name: "Stone / Block Masonry", description: "Natural stone or CMU when true — firm price after site + access check", priceFrom: 0 },
      { name: "Chimney / Veneer / Retaining", description: "Code-aware when required — no bait flat $/sqft or fake same-day build", priceFrom: 0 },
    ],
    heroHints: ["Sqft/access/material/mortar/height assessed before firm price", "Quote before build or repair", "HOA/permit honesty when required", "No bait flat $/sqft fees"],
    ctaLabel: "Get a masonry quote",
    accentHint: "kiln-brick-limestone",
  },
  {
    id: "drywall",
    label: "Drywall",
    defaultTagline: "Hang, finish & repair — quote before we start",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Drywall Hang / New Walls", description: "Sheetrock hang — quote after sqft, access, rooms, texture, and height", priceFrom: 0 },
      { name: "Finish / Texture Match", description: "Smooth, orange-peel, or knockdown when true — firm price after site check", priceFrom: 0 },
      { name: "Patch / Water / Nail Pops / Seams", description: "Repair honesty — no bait flat $/sqft or fake same-day hang", priceFrom: 0 },
    ],
    heroHints: ["Sqft/access/rooms/texture/damage/height assessed before firm price", "Quote before hang, finish, or repair", "HOA/permit honesty when required", "No bait flat $/sqft fees"],
    ctaLabel: "Get a drywall quote",
    accentHint: "gypsum-tape-beige",
  },
  {
    id: "insulation",
    label: "Insulation",
    defaultTagline: "Attic, walls & crawl — quote before we install",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Attic Blow-In / Cellulose", description: "Loose-fill attic — quote after sqft, access, existing R-value, moisture/ventilation, and height", priceFrom: 0 },
      { name: "Batts / Fiberglass", description: "Wall or attic batts when true — firm price after attic-vs-wall-vs-crawl site check", priceFrom: 0 },
      { name: "Spray Foam / Crawl / Walls", description: "Closed/open cell when true — no bait flat $/sqft or fake same-day install", priceFrom: 0 },
    ],
    heroHints: ["Sqft/access/attic-vs-wall-vs-crawl/R-value/moisture/height assessed before firm price", "Quote before blow-in, batts, or spray foam", "HOA/permit honesty when required", "No bait flat $/sqft fees"],
    ctaLabel: "Get an insulation quote",
    accentHint: "attic-taupe-insulation-pink",
  },
  {
    id: "tile",
    label: "Tile",
    defaultTagline: "Floor, wall & shower — quote before we set",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Floor / Large-Format Tile", description: "Porcelain or ceramic floors — quote after sqft, access, substrate, material, and grout", priceFrom: 0 },
      { name: "Wall / Backsplash / Shower", description: "Wall and wet-area tile when true — firm price after waterproofing/height site check", priceFrom: 0 },
      { name: "Repair / Regrout / Natural Stone", description: "Repair honesty — no bait flat $/sqft or fake same-day install", priceFrom: 0 },
    ],
    heroHints: ["Sqft/access/substrate/material/grout/height/waterproofing assessed before firm price", "Quote before install or repair", "HOA/permit honesty when required", "No bait flat $/sqft fees"],
    ctaLabel: "Get a tile quote",
    accentHint: "porcelain-slate-grout-beige",
  },
  {
    id: "cabinets",
    label: "Cabinets",
    defaultTagline: "Kitchen & bath — quote before we build or reface",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "New Kitchen / Bath Cabinets", description: "Custom or semi-custom — quote after linear-ft, access, layout, and material site measure", priceFrom: 0 },
      { name: "Cabinet Refacing / Hardware", description: "Doors, drawers, soft-close, hardware when true — firm price after existing-vs-new check", priceFrom: 0 },
      { name: "Laundry / Garage / Built-ins", description: "Secondary spaces when true — no bait flat $/lf or $/cabinet or fake same-day install", priceFrom: 0 },
    ],
    heroHints: ["Linear-ft/access/existing-vs-new/material/layout measured before firm price", "Quote before install or refacing", "HOA/permit honesty when required", "No bait flat $/lf or $/cabinet fees"],
    ctaLabel: "Get a cabinet quote",
    accentHint: "walnut-charcoal-brass",
  },
  {
    id: "countertops",
    label: "Countertops",
    defaultTagline: "Quartz, granite & more — quote before we fabricate",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Kitchen Countertops", description: "Quartz, granite, marble, laminate, or butcher-block when true — quote after sqft/linear, edge profile, sink cutout, and access/stories", priceFrom: 0 },
      { name: "Bath / Vanity Tops", description: "Vanity and bath tops when true — firm price after existing-vs-new and material site measure", priceFrom: 0 },
      { name: "Fabrication / Edge / Cutouts", description: "Edge profiles and sink cutouts — no bait flat $/sqft or $/lf or fake same-day install", priceFrom: 0 },
    ],
    heroHints: ["Sqft/linear/edge/sink-cutout/access/stories/material assessed before firm price", "Quote before install", "HOA/permit honesty when required", "No bait flat $/sqft or $/lf fees"],
    ctaLabel: "Get a countertop quote",
    accentHint: "quartz-slate-brass-veining",
  },
  {
    id: "foundation_repair",
    label: "Foundation repair",
    defaultTagline: "Inspection-first foundation repair — quote before we dig",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Foundation Inspection", description: "Soil, drainage, crack pattern, pier vs slab, access, and stories assessed before firm price", priceFrom: 0 },
      { name: "Pier & Beam / Slab Repair", description: "Repair scope after inspection — no bait flat $/lf or $/pier packages", priceFrom: 0 },
      { name: "Drainage & Stabilization", description: "Drainage and stabilization when true — licensed contractor / engineer honesty; no fake same-day fix", priceFrom: 0 },
    ],
    heroHints: ["Soil/drainage/crack/pier-vs-slab/access assessed before firm price", "Quote before repair", "Licensed contractor / engineer honesty when true", "No bait flat $/lf or $/pier fees"],
    ctaLabel: "Get a foundation quote",
    accentHint: "foundation-charcoal-copper",
  },
  {
    id: "irrigation",
    label: "Irrigation",
    defaultTagline: "Zone-first irrigation quotes — assess before we dig or rewire",
    defaultHours: {
      mon: "7:00 AM – 5:00 PM",
      tue: "7:00 AM – 5:00 PM",
      wed: "7:00 AM – 5:00 PM",
      thu: "7:00 AM – 5:00 PM",
      fri: "7:00 AM – 5:00 PM",
      sat: "8:00 AM – 12:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Sprinkler Repair", description: "Zone count, lawn size, existing system, controller type, and access assessed before firm price — no bait flat $/zone or $/head", priceFrom: 0 },
      { name: "New System Install", description: "Drip vs spray, winterization, and layout after site assess — HOA/permit honesty when true; no fake same-day install", priceFrom: 0 },
      { name: "Controller / Winterization", description: "Controller upgrades and seasonal winterization when true — licensed plumber/irrigation honesty when required", priceFrom: 0 },
    ],
    heroHints: ["Zones/lawn size/existing vs new/controller assessed before firm price", "Quote before install or repair", "HOA/permit & licensed plumber/irrigation honesty when required", "No bait flat $/zone or $/head fees"],
    ctaLabel: "Get an irrigation quote",
    accentHint: "irrigation-green-sky-spray",
  },


  {
    id: "solar",
    label: "Solar",
    defaultTagline: "Roof-and-utility-first solar quotes — assess before we price panels",
    defaultHours: {
      mon: "8:00 AM – 5:00 PM",
      tue: "8:00 AM – 5:00 PM",
      wed: "8:00 AM – 5:00 PM",
      thu: "8:00 AM – 5:00 PM",
      fri: "8:00 AM – 5:00 PM",
      sat: "9:00 AM – 1:00 PM",
      sun: "Closed",
    },
    defaultServices: [
      { name: "Solar Site Assessment", description: "Roof size/condition/orientation/shading, utility/net-metering/interconnect, existing vs new, and battery storage assessed before firm price — no bait flat $/watt", priceFrom: 0 },
      { name: "Panel + Inverter Quote", description: "System scope after roof/utility assess — HOA/permit honesty when true; no fake same-day install", priceFrom: 0 },
      { name: "Battery Storage Option", description: "Battery yes/no after load and interconnect review — licensed electrician/solar contractor honesty when required", priceFrom: 0 },
    ],
    heroHints: ["Roof/utility/net-metering/battery assessed before firm price", "Quote before install", "HOA/permit & licensed electrician/solar contractor honesty when required", "No bait flat $/watt fees"],
    ctaLabel: "Get a solar quote",
    accentHint: "solar-slate-gold-amber",
  },


];

export function getTemplate(niche: string): NicheTemplate | undefined {
  return NICHE_TEMPLATES.find((t) => t.id === niche);
}
